In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:\SMT 6 Project\Data Analytics\model-rnn\data\match.csv")

In [3]:
df

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City
1,2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City
2,3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City
3,4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City
4,5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4489,38,2018-04-15,16:00,Premier League,Matchweek 34,Sun,Away,W,1.0,0.0,...,Match Report,NaN,10.0,4.0,18.1,0.0,0.0,0.0,2017,West Bromwich Albion
4490,39,2018-04-21,12:30,Premier League,Matchweek 35,Sat,Home,D,2.0,2.0,...,Match Report,NaN,13.0,6.0,17.7,0.0,0.0,0.0,2017,West Bromwich Albion
4491,40,2018-04-28,15:00,Premier League,Matchweek 36,Sat,Away,W,1.0,0.0,...,Match Report,NaN,9.0,2.0,20.1,0.0,0.0,0.0,2017,West Bromwich Albion
4492,41,2018-05-05,15:00,Premier League,Matchweek 37,Sat,Home,W,1.0,0.0,...,Match Report,NaN,9.0,1.0,10.2,0.0,0.0,0.0,2017,West Bromwich Albion
4493,42,2018-05-13,15:00,Premier League,Matchweek 38,Sun,Away,L,0.0,2.0,...,Match Report,NaN,7.0,1.0,24.8,1.0,0.0,0.0,2017,West Bromwich Albion

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4494 entries, 0 to 4493
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    4494 non-null   int64
 1   date          4494 non-null   object
 2   time          4494 non-null   object
 3   comp          4494 non-null   object
 4   round         4494 non-null   object
 5   day           4494 non-null   object
 6   venue         4494 non-null   object
 7   result        4494 non-null   object
 8   gf            4494 non-null   float64
 9   ga            4494 non-null   float64
 10  opponent      4494 non-null   object
 11  xg            4494 non-null   float64
 12  xga           4494 non-null   float64
 13  poss          4494 non-null   float64
 14  attendance    3614 non-null   float64
 15  captain       4494 non-null   object
 16  formation     4494 non-null   object
 17  referee       4494 non-null   object
 18  match report  4494 non-null   object
 19  notes         0 non-null      float64
 20  sh            4494 non-null   float64
 21  sot           4494 non-null   float64
 22  dist          4491 non-null   float64
 23  fk            4494 non-null   float64
 24  pk            4494 non-null   float64
 25  pkatt         4494 non-null   float64
 26  season        4494 non-null   int64
 27  team          4494 non-null   object
dtypes: float64(13), int64(2), object(13)
memory usage: 983.2+ KB